# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CDC_Viewer_gui55.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(272, 617)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CDC_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.plotArea = QtWidgets.QVBoxLayout()
        self.plotArea.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotArea.setObjectName("plotArea")
        self.gridLayout.addLayout(self.plotArea, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(270, 0))
        self.frame.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.presetsBox = QtWidgets.QGroupBox(self.frame)
        self.presetsBox.setObjectName("presetsBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.presetsBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnConnect = QtWidgets.QPushButton(self.presetsBox)
        self.btnConnect.setEnabled(True)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_6.addWidget(self.btnConnect, 1, 3, 1, 1)
        self.serialSlots = QtWidgets.QComboBox(self.presetsBox)
        self.serialSlots.setObjectName("serialSlots")
        self.gridLayout_6.addWidget(self.serialSlots, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.presetsBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.SensorNo = QtWidgets.QSpinBox(self.presetsBox)
        self.SensorNo.setMinimum(1)
        self.SensorNo.setMaximum(8)
        self.SensorNo.setObjectName("SensorNo")
        self.gridLayout_6.addWidget(self.SensorNo, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.presetsBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 2, 1, 1)
        self.comboLiveView = QtWidgets.QComboBox(self.presetsBox)
        self.comboLiveView.setObjectName("comboLiveView")
        self.comboLiveView.addItem("")
        self.comboLiveView.addItem("")
        self.comboLiveView.addItem("")
        self.comboLiveView.addItem("")
        self.gridLayout_6.addWidget(self.comboLiveView, 2, 3, 1, 1)
        self.btnRefresh = QtWidgets.QPushButton(self.presetsBox)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout_6.addWidget(self.btnRefresh, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.presetsBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.autoSetDirectory = QtWidgets.QPushButton(self.groupBox_5)
        self.autoSetDirectory.setEnabled(True)
        self.autoSetDirectory.setObjectName("autoSetDirectory")
        self.gridLayout_7.addWidget(self.autoSetDirectory, 3, 2, 1, 1)
        self.autoSetFilename = QtWidgets.QPushButton(self.groupBox_5)
        self.autoSetFilename.setEnabled(False)
        self.autoSetFilename.setObjectName("autoSetFilename")
        self.gridLayout_7.addWidget(self.autoSetFilename, 6, 2, 1, 1)
        self.cboxAutosave = QtWidgets.QCheckBox(self.groupBox_5)
        self.cboxAutosave.setObjectName("cboxAutosave")
        self.gridLayout_7.addWidget(self.cboxAutosave, 7, 0, 1, 1)
        self.autoDirectory = QtWidgets.QLineEdit(self.groupBox_5)
        self.autoDirectory.setEnabled(True)
        self.autoDirectory.setReadOnly(True)
        self.autoDirectory.setObjectName("autoDirectory")
        self.gridLayout_7.addWidget(self.autoDirectory, 3, 0, 1, 2)
        self.autoFilename = QtWidgets.QLineEdit(self.groupBox_5)
        self.autoFilename.setObjectName("autoFilename")
        self.gridLayout_7.addWidget(self.autoFilename, 6, 0, 1, 2)
        self.btnSave = QtWidgets.QPushButton(self.groupBox_5)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_7.addWidget(self.btnSave, 7, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.selectLCD = QtWidgets.QComboBox(self.groupBox_4)
        self.selectLCD.setEnabled(False)
        self.selectLCD.setObjectName("selectLCD")
        self.gridLayout_4.addWidget(self.selectLCD, 9, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 8, 0, 1, 1)
        self.lcdVoltage = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdVoltage.setDigitCount(4)
        self.lcdVoltage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdVoltage.setObjectName("lcdVoltage")
        self.gridLayout_4.addWidget(self.lcdVoltage, 9, 3, 1, 2)
        self.btnacquisition = QtWidgets.QPushButton(self.groupBox_4)
        self.btnacquisition.setEnabled(False)
        self.btnacquisition.setObjectName("btnacquisition")
        self.gridLayout_4.addWidget(self.btnacquisition, 0, 0, 1, 5)
        self.lcdSerRead = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lcdSerRead.setFont(font)
        self.lcdSerRead.setSmallDecimalPoint(True)
        self.lcdSerRead.setDigitCount(7)
        self.lcdSerRead.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdSerRead.setProperty("value", 0.0)
        self.lcdSerRead.setObjectName("lcdSerRead")
        self.gridLayout_4.addWidget(self.lcdSerRead, 9, 1, 1, 2)
        self.lcdTime = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdTime.setAutoFillBackground(False)
        self.lcdTime.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdTime.setSmallDecimalPoint(True)
        self.lcdTime.setDigitCount(7)
        self.lcdTime.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTime.setObjectName("lcdTime")
        self.gridLayout_4.addWidget(self.lcdTime, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 8, 1, 1, 1)
        self.label_V = QtWidgets.QLabel(self.groupBox_4)
        self.label_V.setObjectName("label_V")
        self.gridLayout_4.addWidget(self.label_V, 8, 3, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pbnTrigger = QtWidgets.QPushButton(self.groupBox)
        self.pbnTrigger.setEnabled(False)
        self.pbnTrigger.setCheckable(False)
        self.pbnTrigger.setChecked(False)
        self.pbnTrigger.setDefault(False)
        self.pbnTrigger.setFlat(False)
        self.pbnTrigger.setObjectName("pbnTrigger")
        self.gridLayout_5.addWidget(self.pbnTrigger, 0, 1, 1, 1)
        self.extTrigger = QtWidgets.QCheckBox(self.groupBox)
        self.extTrigger.setEnabled(True)
        self.extTrigger.setChecked(True)
        self.extTrigger.setAutoExclusive(False)
        self.extTrigger.setObjectName("extTrigger")
        self.gridLayout_5.addWidget(self.extTrigger, 0, 0, 1, 1)
        self.modeBox = QtWidgets.QFrame(self.groupBox)
        self.modeBox.setEnabled(False)
        self.modeBox.setObjectName("modeBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.modeBox)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbRun = QtWidgets.QLabel(self.modeBox)
        self.lbRun.setAutoFillBackground(False)
        self.lbRun.setObjectName("lbRun")
        self.gridLayout_3.addWidget(self.lbRun, 8, 1, 1, 1)
        self.timeBox = QtWidgets.QDoubleSpinBox(self.modeBox)
        self.timeBox.setProperty("value", 0.0)
        self.timeBox.setObjectName("timeBox")
        self.gridLayout_3.addWidget(self.timeBox, 7, 2, 1, 1)
        self.rbtnAuto = QtWidgets.QRadioButton(self.modeBox)
        self.rbtnAuto.setObjectName("rbtnAuto")
        self.gridLayout_3.addWidget(self.rbtnAuto, 0, 1, 1, 2)
        self.timeSet = QtWidgets.QPushButton(self.modeBox)
        self.timeSet.setChecked(False)
        self.timeSet.setObjectName("timeSet")
        self.gridLayout_3.addWidget(self.timeSet, 7, 3, 1, 1)
        self.cboxRestart = QtWidgets.QCheckBox(self.modeBox)
        self.cboxRestart.setObjectName("cboxRestart")
        self.gridLayout_3.addWidget(self.cboxRestart, 6, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.modeBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 7, 1, 1, 1)
        self.autoSetNo = QtWidgets.QPushButton(self.modeBox)
        self.autoSetNo.setObjectName("autoSetNo")
        self.gridLayout_3.addWidget(self.autoSetNo, 8, 3, 1, 1)
        self.rbtnTime = QtWidgets.QRadioButton(self.modeBox)
        self.rbtnTime.setToolTip("")
        self.rbtnTime.setToolTipDuration(3)
        self.rbtnTime.setObjectName("rbtnTime")
        self.gridLayout_3.addWidget(self.rbtnTime, 6, 1, 1, 2)
        self.autoCurrentNo = QtWidgets.QSpinBox(self.modeBox)
        self.autoCurrentNo.setProperty("value", 1)
        self.autoCurrentNo.setDisplayIntegerBase(10)
        self.autoCurrentNo.setObjectName("autoCurrentNo")
        self.gridLayout_3.addWidget(self.autoCurrentNo, 8, 2, 1, 1)
        self.ToggleTrigger = QtWidgets.QPushButton(self.modeBox)
        self.ToggleTrigger.setEnabled(False)
        self.ToggleTrigger.setObjectName("ToggleTrigger")
        self.gridLayout_3.addWidget(self.ToggleTrigger, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.modeBox, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.PlotFrame = QtWidgets.QFrame(self.frame)
        self.PlotFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.PlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PlotFrame.setObjectName("PlotFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PlotFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BoxPlot = QtWidgets.QGroupBox(self.PlotFrame)
        self.BoxPlot.setEnabled(False)
        self.BoxPlot.setCheckable(False)
        self.BoxPlot.setObjectName("BoxPlot")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.BoxPlot)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.BoxPlot)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.BoxPlot)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.BoxPlot)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.setymax = QtWidgets.QSpinBox(self.BoxPlot)
        self.setymax.setMaximum(25000)
        self.setymax.setSingleStep(10)
        self.setymax.setProperty("value", 2000)
        self.setymax.setDisplayIntegerBase(10)
        self.setymax.setObjectName("setymax")
        self.gridLayout_2.addWidget(self.setymax, 3, 3, 1, 1)
        self.setxmax = QtWidgets.QSpinBox(self.BoxPlot)
        self.setxmax.setMaximum(50000)
        self.setxmax.setSingleStep(60)
        self.setxmax.setProperty("value", 900)
        self.setxmax.setObjectName("setxmax")
        self.gridLayout_2.addWidget(self.setxmax, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.BoxPlot)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.setymin = QtWidgets.QSpinBox(self.BoxPlot)
        self.setymin.setMaximum(25000)
        self.setymin.setSingleStep(10)
        self.setymin.setProperty("value", 0)
        self.setymin.setObjectName("setymin")
        self.gridLayout_2.addWidget(self.setymin, 3, 1, 1, 1)
        self.setxmin = QtWidgets.QSpinBox(self.BoxPlot)
        self.setxmin.setMaximum(10000)
        self.setxmin.setSingleStep(60)
        self.setxmin.setProperty("value", 0)
        self.setxmin.setObjectName("setxmin")
        self.gridLayout_2.addWidget(self.setxmin, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.BoxPlot)
        self.verticalLayout.addWidget(self.PlotFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 272, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.comboLiveView.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.autoSetFilename, self.rbtnAuto)
        MainWindow.setTabOrder(self.rbtnAuto, self.timeBox)
        MainWindow.setTabOrder(self.timeBox, self.timeSet)
        MainWindow.setTabOrder(self.timeSet, self.rbtnTime)
        MainWindow.setTabOrder(self.rbtnTime, self.cboxRestart)
        MainWindow.setTabOrder(self.cboxRestart, self.autoCurrentNo)
        MainWindow.setTabOrder(self.autoCurrentNo, self.autoSetNo)
        MainWindow.setTabOrder(self.autoSetNo, self.setxmin)
        MainWindow.setTabOrder(self.setxmin, self.setxmax)
        MainWindow.setTabOrder(self.setxmax, self.setymin)
        MainWindow.setTabOrder(self.setymin, self.setymax)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.presetsBox.setTitle(_translate("MainWindow", "Presets"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_12.setText(_translate("MainWindow", "Clients"))
        self.label_9.setText(_translate("MainWindow", "View columns"))
        self.comboLiveView.setItemText(0, _translate("MainWindow", "0"))
        self.comboLiveView.setItemText(1, _translate("MainWindow", "1"))
        self.comboLiveView.setItemText(2, _translate("MainWindow", "2"))
        self.comboLiveView.setItemText(3, _translate("MainWindow", "3"))
        self.btnRefresh.setText(_translate("MainWindow", "Get Ports"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Save Options"))
        self.autoSetDirectory.setText(_translate("MainWindow", "Set Directory"))
        self.autoSetFilename.setText(_translate("MainWindow", "Set Fileame"))
        self.cboxAutosave.setText(_translate("MainWindow", "Autosave off"))
        self.btnSave.setText(_translate("MainWindow", "SnapSave"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data acquisition:"))
        self.label_6.setText(_translate("MainWindow", "Elapsed sec"))
        self.label_13.setText(_translate("MainWindow", "Detector"))
        self.btnacquisition.setText(_translate("MainWindow", "Start acquisition"))
        self.label_5.setText(_translate("MainWindow", "Reading  in a.u."))
        self.label_V.setText(_translate("MainWindow", "Supply voltage"))
        self.groupBox.setTitle(_translate("MainWindow", "Trigger Options"))
        self.pbnTrigger.setText(_translate("MainWindow", "Inject"))
        self.extTrigger.setText(_translate("MainWindow", "Hardware Trigger"))
        self.lbRun.setText(_translate("MainWindow", "Next run"))
        self.rbtnAuto.setText(_translate("MainWindow", "Start/Stop-Trigger"))
        self.timeSet.setText(_translate("MainWindow", "Set Timer"))
        self.cboxRestart.setText(_translate("MainWindow", "no restart"))
        self.label_8.setText(_translate("MainWindow", "Timer /min"))
        self.autoSetNo.setText(_translate("MainWindow", "Set Number"))
        self.rbtnTime.setText(_translate("MainWindow", "Start-Trigger Stop-Time"))
        self.ToggleTrigger.setText(_translate("MainWindow", "Toggle Trigger"))
        self.BoxPlot.setTitle(_translate("MainWindow", "Plot Options"))
        self.label_3.setText(_translate("MainWindow", "y min"))
        self.label_2.setText(_translate("MainWindow", "x max"))
        self.label_4.setText(_translate("MainWindow", "y max"))
        self.label.setText(_translate("MainWindow", "x min"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

